/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as valcoreReactiveDispatcherSol from "./ValcoreReactiveDispatcher.sol";
export type { valcoreReactiveDispatcherSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as reactiveLib from "./reactive-lib";
export type { reactiveLib };
export type { StablecoinMock } from "./StablecoinMock";
export type { ValcoreReactiveReceiver } from "./ValcoreReactiveReceiver";
export type { ValcoreReactiveTrigger } from "./ValcoreReactiveTrigger";
export type { ValcoreV1 } from "./ValcoreV1";
