/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IReactive {
  export type LogRecordStruct = {
    chain_id: BigNumberish;
    _contract: AddressLike;
    topic_0: BigNumberish;
    topic_1: BigNumberish;
    topic_2: BigNumberish;
    topic_3: BigNumberish;
    data: BytesLike;
    block_number: BigNumberish;
    op_code: BigNumberish;
    block_hash: BigNumberish;
    tx_hash: BigNumberish;
    log_index: BigNumberish;
  };

  export type LogRecordStructOutput = [
    chain_id: bigint,
    _contract: string,
    topic_0: bigint,
    topic_1: bigint,
    topic_2: bigint,
    topic_3: bigint,
    data: string,
    block_number: bigint,
    op_code: bigint,
    block_hash: bigint,
    tx_hash: bigint,
    log_index: bigint
  ] & {
    chain_id: bigint;
    _contract: string;
    topic_0: bigint;
    topic_1: bigint;
    topic_2: bigint;
    topic_3: bigint;
    data: string;
    block_number: bigint;
    op_code: bigint;
    block_hash: bigint;
    tx_hash: bigint;
    log_index: bigint;
  };
}

export interface ValcoreReactiveDispatcherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateSubscription"
      | "coverDebt"
      | "destinationChainId"
      | "destinationReceiver"
      | "dispatch"
      | "nextRequestId"
      | "operator"
      | "pay"
      | "react"
      | "setOperator"
      | "subscriptionActive"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Callback"
      | "DispatchForwarded"
      | "DispatchRequested"
      | "OperatorUpdated"
      | "ReactInvoked"
      | "SubscriptionActivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "coverDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "destinationChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "destinationReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "pay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "react",
    values: [IReactive.LogRecordStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "coverDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "destinationChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destinationReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "react", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CallbackEvent {
  export type InputTuple = [
    chain_id: BigNumberish,
    _contract: AddressLike,
    gas_limit: BigNumberish,
    payload: BytesLike
  ];
  export type OutputTuple = [
    chain_id: bigint,
    _contract: string,
    gas_limit: bigint,
    payload: string
  ];
  export interface OutputObject {
    chain_id: bigint;
    _contract: string;
    gas_limit: bigint;
    payload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DispatchForwardedEvent {
  export type InputTuple = [requestId: BigNumberish, gasLimit: BigNumberish];
  export type OutputTuple = [requestId: bigint, gasLimit: bigint];
  export interface OutputObject {
    requestId: bigint;
    gasLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DispatchRequestedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [
    previousOperator: AddressLike,
    newOperator: AddressLike
  ];
  export type OutputTuple = [previousOperator: string, newOperator: string];
  export interface OutputObject {
    previousOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactInvokedEvent {
  export type InputTuple = [
    topic0: BigNumberish,
    topic1: BigNumberish,
    sourceContract: AddressLike
  ];
  export type OutputTuple = [
    topic0: bigint,
    topic1: bigint,
    sourceContract: string
  ];
  export interface OutputObject {
    topic0: bigint;
    topic1: bigint;
    sourceContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionActivatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    sourceContract: AddressLike,
    topic0: BigNumberish
  ];
  export type OutputTuple = [
    chainId: bigint,
    sourceContract: string,
    topic0: bigint
  ];
  export interface OutputObject {
    chainId: bigint;
    sourceContract: string;
    topic0: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValcoreReactiveDispatcher extends BaseContract {
  connect(runner?: ContractRunner | null): ValcoreReactiveDispatcher;
  waitForDeployment(): Promise<this>;

  interface: ValcoreReactiveDispatcherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateSubscription: TypedContractMethod<[], [void], "nonpayable">;

  coverDebt: TypedContractMethod<[], [void], "nonpayable">;

  destinationChainId: TypedContractMethod<[], [bigint], "view">;

  destinationReceiver: TypedContractMethod<[], [string], "view">;

  dispatch: TypedContractMethod<
    [payload: BytesLike, gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextRequestId: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  pay: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  react: TypedContractMethod<
    [log: IReactive.LogRecordStruct],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  subscriptionActive: TypedContractMethod<[], [boolean], "view">;

  withdraw: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateSubscription"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coverDebt"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "destinationChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "destinationReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dispatch"
  ): TypedContractMethod<
    [payload: BytesLike, gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "react"
  ): TypedContractMethod<
    [log: IReactive.LogRecordStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptionActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Callback"
  ): TypedContractEvent<
    CallbackEvent.InputTuple,
    CallbackEvent.OutputTuple,
    CallbackEvent.OutputObject
  >;
  getEvent(
    key: "DispatchForwarded"
  ): TypedContractEvent<
    DispatchForwardedEvent.InputTuple,
    DispatchForwardedEvent.OutputTuple,
    DispatchForwardedEvent.OutputObject
  >;
  getEvent(
    key: "DispatchRequested"
  ): TypedContractEvent<
    DispatchRequestedEvent.InputTuple,
    DispatchRequestedEvent.OutputTuple,
    DispatchRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReactInvoked"
  ): TypedContractEvent<
    ReactInvokedEvent.InputTuple,
    ReactInvokedEvent.OutputTuple,
    ReactInvokedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionActivated"
  ): TypedContractEvent<
    SubscriptionActivatedEvent.InputTuple,
    SubscriptionActivatedEvent.OutputTuple,
    SubscriptionActivatedEvent.OutputObject
  >;

  filters: {
    "Callback(uint256,address,uint64,bytes)": TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;
    Callback: TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;

    "DispatchForwarded(uint256,uint64)": TypedContractEvent<
      DispatchForwardedEvent.InputTuple,
      DispatchForwardedEvent.OutputTuple,
      DispatchForwardedEvent.OutputObject
    >;
    DispatchForwarded: TypedContractEvent<
      DispatchForwardedEvent.InputTuple,
      DispatchForwardedEvent.OutputTuple,
      DispatchForwardedEvent.OutputObject
    >;

    "DispatchRequested(uint256)": TypedContractEvent<
      DispatchRequestedEvent.InputTuple,
      DispatchRequestedEvent.OutputTuple,
      DispatchRequestedEvent.OutputObject
    >;
    DispatchRequested: TypedContractEvent<
      DispatchRequestedEvent.InputTuple,
      DispatchRequestedEvent.OutputTuple,
      DispatchRequestedEvent.OutputObject
    >;

    "OperatorUpdated(address,address)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "ReactInvoked(uint256,uint256,address)": TypedContractEvent<
      ReactInvokedEvent.InputTuple,
      ReactInvokedEvent.OutputTuple,
      ReactInvokedEvent.OutputObject
    >;
    ReactInvoked: TypedContractEvent<
      ReactInvokedEvent.InputTuple,
      ReactInvokedEvent.OutputTuple,
      ReactInvokedEvent.OutputObject
    >;

    "SubscriptionActivated(uint256,address,uint256)": TypedContractEvent<
      SubscriptionActivatedEvent.InputTuple,
      SubscriptionActivatedEvent.OutputTuple,
      SubscriptionActivatedEvent.OutputObject
    >;
    SubscriptionActivated: TypedContractEvent<
      SubscriptionActivatedEvent.InputTuple,
      SubscriptionActivatedEvent.OutputTuple,
      SubscriptionActivatedEvent.OutputObject
    >;
  };
}
