/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ValcoreReactiveTriggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dispatcher"
      | "owner"
      | "setDispatcher"
      | "transferOwnership"
      | "trigger"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DispatchTrigger"
      | "DispatcherUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dispatcher",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDispatcher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trigger",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "dispatcher", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDispatcher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trigger", data: BytesLike): Result;
}

export namespace DispatchTriggerEvent {
  export type InputTuple = [payload: BytesLike, gasLimit: BigNumberish];
  export type OutputTuple = [payload: string, gasLimit: bigint];
  export interface OutputObject {
    payload: string;
    gasLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DispatcherUpdatedEvent {
  export type InputTuple = [
    previousDispatcher: AddressLike,
    newDispatcher: AddressLike
  ];
  export type OutputTuple = [previousDispatcher: string, newDispatcher: string];
  export interface OutputObject {
    previousDispatcher: string;
    newDispatcher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValcoreReactiveTrigger extends BaseContract {
  connect(runner?: ContractRunner | null): ValcoreReactiveTrigger;
  waitForDeployment(): Promise<this>;

  interface: ValcoreReactiveTriggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dispatcher: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setDispatcher: TypedContractMethod<
    [newDispatcher: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trigger: TypedContractMethod<
    [payload: BytesLike, gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dispatcher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDispatcher"
  ): TypedContractMethod<[newDispatcher: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trigger"
  ): TypedContractMethod<
    [payload: BytesLike, gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DispatchTrigger"
  ): TypedContractEvent<
    DispatchTriggerEvent.InputTuple,
    DispatchTriggerEvent.OutputTuple,
    DispatchTriggerEvent.OutputObject
  >;
  getEvent(
    key: "DispatcherUpdated"
  ): TypedContractEvent<
    DispatcherUpdatedEvent.InputTuple,
    DispatcherUpdatedEvent.OutputTuple,
    DispatcherUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DispatchTrigger(bytes,uint64)": TypedContractEvent<
      DispatchTriggerEvent.InputTuple,
      DispatchTriggerEvent.OutputTuple,
      DispatchTriggerEvent.OutputObject
    >;
    DispatchTrigger: TypedContractEvent<
      DispatchTriggerEvent.InputTuple,
      DispatchTriggerEvent.OutputTuple,
      DispatchTriggerEvent.OutputObject
    >;

    "DispatcherUpdated(address,address)": TypedContractEvent<
      DispatcherUpdatedEvent.InputTuple,
      DispatcherUpdatedEvent.OutputTuple,
      DispatcherUpdatedEvent.OutputObject
    >;
    DispatcherUpdated: TypedContractEvent<
      DispatcherUpdatedEvent.InputTuple,
      DispatcherUpdatedEvent.OutputTuple,
      DispatcherUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
