/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ValcoreV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUDITOR_ROLE"
      | "BPS"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_SWAPS"
      | "ORACLE_ROLE"
      | "PAUSER_ROLE"
      | "REWARD_SWEEP_DELAY"
      | "approveFinalization"
      | "approveFinalizationWithIntent"
      | "claim"
      | "commitLineup"
      | "createWeek"
      | "createWeekWithIntent"
      | "emergencyExit"
      | "feeBps"
      | "finalizeWeek"
      | "finalizeWeekWithIntent"
      | "forceFinalizeWeek"
      | "forceFinalizeWeekWithIntent"
      | "forceLockWeek"
      | "forceLockWeekWithIntent"
      | "forceStartWeek"
      | "forceStartWeekWithIntent"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "lifecycleIntentExecuted"
      | "lockWeek"
      | "lockWeekWithIntent"
      | "minDeposit"
      | "pause"
      | "paused"
      | "positions"
      | "principalRatioBps"
      | "rejectFinalization"
      | "rejectFinalizationWithIntent"
      | "renounceRole"
      | "revokeRole"
      | "rewardSweepAvailableAt"
      | "setTestMode"
      | "stablecoin"
      | "startWeek"
      | "startWeekWithIntent"
      | "supportsInterface"
      | "swapLineup"
      | "sweepExpiredReward"
      | "testMode"
      | "treasury"
      | "unpause"
      | "weekStates"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "EmergencyExit"
      | "LifecycleIntentConsumed"
      | "LineupCommitted"
      | "LineupSwapped"
      | "LineupUpdated"
      | "Paused"
      | "ProtocolFeeTransferred"
      | "RewardSwept"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TestModeChanged"
      | "Unpaused"
      | "WeekCreated"
      | "WeekFinalizationRejected"
      | "WeekFinalizePending"
      | "WeekFinalized"
      | "WeekLocked"
      | "WeekStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SWAPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_SWEEP_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveFinalization",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveFinalizationWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "commitLineup",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createWeek",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createWeekWithIntent",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyExit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeWeek",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWeekWithIntent",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceFinalizeWeek",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceFinalizeWeekWithIntent",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceLockWeek",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceLockWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceStartWeek",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceStartWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lifecycleIntentExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockWeek",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "principalRatioBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectFinalization",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectFinalizationWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardSweepAvailableAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startWeek",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapLineup",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepExpiredReward",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "testMode", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "weekStates",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SWAPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_SWEEP_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveFinalizationWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitLineup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createWeek", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceFinalizeWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceFinalizeWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLockWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLockWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceStartWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceStartWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lifecycleIntentExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockWeek", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "principalRatioBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectFinalizationWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardSweepAvailableAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startWeek", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapLineup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sweepExpiredReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testMode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weekStates", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [weekId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyExitEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [weekId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LifecycleIntentConsumedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    action: BigNumberish,
    weekId: BigNumberish,
    caller: AddressLike
  ];
  export type OutputTuple = [
    intentId: string,
    action: bigint,
    weekId: bigint,
    caller: string
  ];
  export interface OutputObject {
    intentId: string;
    action: bigint;
    weekId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineupCommittedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    lineupHash: BytesLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    user: string,
    lineupHash: string,
    deposit: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    lineupHash: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineupSwappedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    lineupHash: BytesLike,
    swapsUsed: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    user: string,
    lineupHash: string,
    swapsUsed: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    lineupHash: string;
    swapsUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineupUpdatedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    lineupHash: BytesLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    user: string,
    lineupHash: string,
    deposit: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    lineupHash: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeTransferredEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    treasury: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [weekId: bigint, treasury: string, amount: bigint];
  export interface OutputObject {
    weekId: bigint;
    treasury: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardSweptEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    user: AddressLike,
    caller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    user: string,
    caller: string,
    amount: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    user: string;
    caller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TestModeChangedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekCreatedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    startAt: BigNumberish,
    lockAt: BigNumberish,
    endAt: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    startAt: bigint,
    lockAt: bigint,
    endAt: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    startAt: bigint;
    lockAt: bigint;
    endAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekFinalizationRejectedEvent {
  export type InputTuple = [weekId: BigNumberish];
  export type OutputTuple = [weekId: bigint];
  export interface OutputObject {
    weekId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekFinalizePendingEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    merkleRoot: BytesLike,
    metadataHash: BytesLike,
    retainedFee: BigNumberish
  ];
  export type OutputTuple = [
    weekId: bigint,
    merkleRoot: string,
    metadataHash: string,
    retainedFee: bigint
  ];
  export interface OutputObject {
    weekId: bigint;
    merkleRoot: string;
    metadataHash: string;
    retainedFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekFinalizedEvent {
  export type InputTuple = [
    weekId: BigNumberish,
    merkleRoot: BytesLike,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    weekId: bigint,
    merkleRoot: string,
    metadataHash: string
  ];
  export interface OutputObject {
    weekId: bigint;
    merkleRoot: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekLockedEvent {
  export type InputTuple = [weekId: BigNumberish];
  export type OutputTuple = [weekId: bigint];
  export interface OutputObject {
    weekId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeekStartedEvent {
  export type InputTuple = [weekId: BigNumberish];
  export type OutputTuple = [weekId: bigint];
  export interface OutputObject {
    weekId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValcoreV1 extends BaseContract {
  connect(runner?: ContractRunner | null): ValcoreV1;
  waitForDeployment(): Promise<this>;

  interface: ValcoreV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  BPS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_SWAPS: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  REWARD_SWEEP_DELAY: TypedContractMethod<[], [bigint], "view">;

  approveFinalization: TypedContractMethod<
    [weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveFinalizationWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<
    [
      weekId: BigNumberish,
      principal: BigNumberish,
      riskPayout: BigNumberish,
      totalWithdraw: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  commitLineup: TypedContractMethod<
    [weekId: BigNumberish, lineupHash: BytesLike, depositAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createWeek: TypedContractMethod<
    [
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emergencyExit: TypedContractMethod<
    [weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  finalizeWeek: TypedContractMethod<
    [
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  finalizeWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  forceFinalizeWeek: TypedContractMethod<
    [
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  forceFinalizeWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  forceLockWeek: TypedContractMethod<
    [weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceLockWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceStartWeek: TypedContractMethod<
    [weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceStartWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lifecycleIntentExecuted: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  lockWeek: TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;

  lockWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  minDeposit: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint, boolean] & {
        principal: bigint;
        risk: bigint;
        forfeitedReward: bigint;
        lineupHash: string;
        swaps: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  principalRatioBps: TypedContractMethod<[], [bigint], "view">;

  rejectFinalization: TypedContractMethod<
    [weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectFinalizationWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rewardSweepAvailableAt: TypedContractMethod<
    [weekId: BigNumberish],
    [bigint],
    "view"
  >;

  setTestMode: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  startWeek: TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;

  startWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  swapLineup: TypedContractMethod<
    [weekId: BigNumberish, newHash: BytesLike],
    [void],
    "nonpayable"
  >;

  sweepExpiredReward: TypedContractMethod<
    [
      weekId: BigNumberish,
      user: AddressLike,
      principal: BigNumberish,
      riskPayout: BigNumberish,
      totalWithdraw: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  testMode: TypedContractMethod<[], [boolean], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  weekStates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        startAt: bigint;
        lockAt: bigint;
        endAt: bigint;
        finalizedAt: bigint;
        status: bigint;
        riskCommitted: bigint;
        retainedFee: bigint;
        merkleRoot: string;
        metadataHash: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SWAPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REWARD_SWEEP_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveFinalization"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveFinalizationWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      principal: BigNumberish,
      riskPayout: BigNumberish,
      totalWithdraw: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitLineup"
  ): TypedContractMethod<
    [weekId: BigNumberish, lineupHash: BytesLike, depositAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWeek"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyExit"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeWeek"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceFinalizeWeek"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceFinalizeWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceLockWeek"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceLockWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceStartWeek"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceStartWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lifecycleIntentExecuted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockWeek"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lockWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint, boolean] & {
        principal: bigint;
        risk: bigint;
        forfeitedReward: bigint;
        lineupHash: string;
        swaps: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "principalRatioBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rejectFinalization"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectFinalizationWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardSweepAvailableAt"
  ): TypedContractMethod<[weekId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setTestMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startWeek"
  ): TypedContractMethod<[weekId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapLineup"
  ): TypedContractMethod<
    [weekId: BigNumberish, newHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sweepExpiredReward"
  ): TypedContractMethod<
    [
      weekId: BigNumberish,
      user: AddressLike,
      principal: BigNumberish,
      riskPayout: BigNumberish,
      totalWithdraw: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "testMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weekStates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        startAt: bigint;
        lockAt: bigint;
        endAt: bigint;
        finalizedAt: bigint;
        status: bigint;
        riskCommitted: bigint;
        retainedFee: bigint;
        merkleRoot: string;
        metadataHash: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyExit"
  ): TypedContractEvent<
    EmergencyExitEvent.InputTuple,
    EmergencyExitEvent.OutputTuple,
    EmergencyExitEvent.OutputObject
  >;
  getEvent(
    key: "LifecycleIntentConsumed"
  ): TypedContractEvent<
    LifecycleIntentConsumedEvent.InputTuple,
    LifecycleIntentConsumedEvent.OutputTuple,
    LifecycleIntentConsumedEvent.OutputObject
  >;
  getEvent(
    key: "LineupCommitted"
  ): TypedContractEvent<
    LineupCommittedEvent.InputTuple,
    LineupCommittedEvent.OutputTuple,
    LineupCommittedEvent.OutputObject
  >;
  getEvent(
    key: "LineupSwapped"
  ): TypedContractEvent<
    LineupSwappedEvent.InputTuple,
    LineupSwappedEvent.OutputTuple,
    LineupSwappedEvent.OutputObject
  >;
  getEvent(
    key: "LineupUpdated"
  ): TypedContractEvent<
    LineupUpdatedEvent.InputTuple,
    LineupUpdatedEvent.OutputTuple,
    LineupUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeTransferred"
  ): TypedContractEvent<
    ProtocolFeeTransferredEvent.InputTuple,
    ProtocolFeeTransferredEvent.OutputTuple,
    ProtocolFeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardSwept"
  ): TypedContractEvent<
    RewardSweptEvent.InputTuple,
    RewardSweptEvent.OutputTuple,
    RewardSweptEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TestModeChanged"
  ): TypedContractEvent<
    TestModeChangedEvent.InputTuple,
    TestModeChangedEvent.OutputTuple,
    TestModeChangedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WeekCreated"
  ): TypedContractEvent<
    WeekCreatedEvent.InputTuple,
    WeekCreatedEvent.OutputTuple,
    WeekCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WeekFinalizationRejected"
  ): TypedContractEvent<
    WeekFinalizationRejectedEvent.InputTuple,
    WeekFinalizationRejectedEvent.OutputTuple,
    WeekFinalizationRejectedEvent.OutputObject
  >;
  getEvent(
    key: "WeekFinalizePending"
  ): TypedContractEvent<
    WeekFinalizePendingEvent.InputTuple,
    WeekFinalizePendingEvent.OutputTuple,
    WeekFinalizePendingEvent.OutputObject
  >;
  getEvent(
    key: "WeekFinalized"
  ): TypedContractEvent<
    WeekFinalizedEvent.InputTuple,
    WeekFinalizedEvent.OutputTuple,
    WeekFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "WeekLocked"
  ): TypedContractEvent<
    WeekLockedEvent.InputTuple,
    WeekLockedEvent.OutputTuple,
    WeekLockedEvent.OutputObject
  >;
  getEvent(
    key: "WeekStarted"
  ): TypedContractEvent<
    WeekStartedEvent.InputTuple,
    WeekStartedEvent.OutputTuple,
    WeekStartedEvent.OutputObject
  >;

  filters: {
    "Claimed(uint256,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "EmergencyExit(uint256,address,uint256)": TypedContractEvent<
      EmergencyExitEvent.InputTuple,
      EmergencyExitEvent.OutputTuple,
      EmergencyExitEvent.OutputObject
    >;
    EmergencyExit: TypedContractEvent<
      EmergencyExitEvent.InputTuple,
      EmergencyExitEvent.OutputTuple,
      EmergencyExitEvent.OutputObject
    >;

    "LifecycleIntentConsumed(bytes32,uint8,uint256,address)": TypedContractEvent<
      LifecycleIntentConsumedEvent.InputTuple,
      LifecycleIntentConsumedEvent.OutputTuple,
      LifecycleIntentConsumedEvent.OutputObject
    >;
    LifecycleIntentConsumed: TypedContractEvent<
      LifecycleIntentConsumedEvent.InputTuple,
      LifecycleIntentConsumedEvent.OutputTuple,
      LifecycleIntentConsumedEvent.OutputObject
    >;

    "LineupCommitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      LineupCommittedEvent.InputTuple,
      LineupCommittedEvent.OutputTuple,
      LineupCommittedEvent.OutputObject
    >;
    LineupCommitted: TypedContractEvent<
      LineupCommittedEvent.InputTuple,
      LineupCommittedEvent.OutputTuple,
      LineupCommittedEvent.OutputObject
    >;

    "LineupSwapped(uint256,address,bytes32,uint8)": TypedContractEvent<
      LineupSwappedEvent.InputTuple,
      LineupSwappedEvent.OutputTuple,
      LineupSwappedEvent.OutputObject
    >;
    LineupSwapped: TypedContractEvent<
      LineupSwappedEvent.InputTuple,
      LineupSwappedEvent.OutputTuple,
      LineupSwappedEvent.OutputObject
    >;

    "LineupUpdated(uint256,address,bytes32,uint256)": TypedContractEvent<
      LineupUpdatedEvent.InputTuple,
      LineupUpdatedEvent.OutputTuple,
      LineupUpdatedEvent.OutputObject
    >;
    LineupUpdated: TypedContractEvent<
      LineupUpdatedEvent.InputTuple,
      LineupUpdatedEvent.OutputTuple,
      LineupUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProtocolFeeTransferred(uint256,address,uint256)": TypedContractEvent<
      ProtocolFeeTransferredEvent.InputTuple,
      ProtocolFeeTransferredEvent.OutputTuple,
      ProtocolFeeTransferredEvent.OutputObject
    >;
    ProtocolFeeTransferred: TypedContractEvent<
      ProtocolFeeTransferredEvent.InputTuple,
      ProtocolFeeTransferredEvent.OutputTuple,
      ProtocolFeeTransferredEvent.OutputObject
    >;

    "RewardSwept(uint256,address,address,uint256)": TypedContractEvent<
      RewardSweptEvent.InputTuple,
      RewardSweptEvent.OutputTuple,
      RewardSweptEvent.OutputObject
    >;
    RewardSwept: TypedContractEvent<
      RewardSweptEvent.InputTuple,
      RewardSweptEvent.OutputTuple,
      RewardSweptEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TestModeChanged(bool)": TypedContractEvent<
      TestModeChangedEvent.InputTuple,
      TestModeChangedEvent.OutputTuple,
      TestModeChangedEvent.OutputObject
    >;
    TestModeChanged: TypedContractEvent<
      TestModeChangedEvent.InputTuple,
      TestModeChangedEvent.OutputTuple,
      TestModeChangedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WeekCreated(uint256,uint64,uint64,uint64)": TypedContractEvent<
      WeekCreatedEvent.InputTuple,
      WeekCreatedEvent.OutputTuple,
      WeekCreatedEvent.OutputObject
    >;
    WeekCreated: TypedContractEvent<
      WeekCreatedEvent.InputTuple,
      WeekCreatedEvent.OutputTuple,
      WeekCreatedEvent.OutputObject
    >;

    "WeekFinalizationRejected(uint256)": TypedContractEvent<
      WeekFinalizationRejectedEvent.InputTuple,
      WeekFinalizationRejectedEvent.OutputTuple,
      WeekFinalizationRejectedEvent.OutputObject
    >;
    WeekFinalizationRejected: TypedContractEvent<
      WeekFinalizationRejectedEvent.InputTuple,
      WeekFinalizationRejectedEvent.OutputTuple,
      WeekFinalizationRejectedEvent.OutputObject
    >;

    "WeekFinalizePending(uint256,bytes32,bytes32,uint256)": TypedContractEvent<
      WeekFinalizePendingEvent.InputTuple,
      WeekFinalizePendingEvent.OutputTuple,
      WeekFinalizePendingEvent.OutputObject
    >;
    WeekFinalizePending: TypedContractEvent<
      WeekFinalizePendingEvent.InputTuple,
      WeekFinalizePendingEvent.OutputTuple,
      WeekFinalizePendingEvent.OutputObject
    >;

    "WeekFinalized(uint256,bytes32,bytes32)": TypedContractEvent<
      WeekFinalizedEvent.InputTuple,
      WeekFinalizedEvent.OutputTuple,
      WeekFinalizedEvent.OutputObject
    >;
    WeekFinalized: TypedContractEvent<
      WeekFinalizedEvent.InputTuple,
      WeekFinalizedEvent.OutputTuple,
      WeekFinalizedEvent.OutputObject
    >;

    "WeekLocked(uint256)": TypedContractEvent<
      WeekLockedEvent.InputTuple,
      WeekLockedEvent.OutputTuple,
      WeekLockedEvent.OutputObject
    >;
    WeekLocked: TypedContractEvent<
      WeekLockedEvent.InputTuple,
      WeekLockedEvent.OutputTuple,
      WeekLockedEvent.OutputObject
    >;

    "WeekStarted(uint256)": TypedContractEvent<
      WeekStartedEvent.InputTuple,
      WeekStartedEvent.OutputTuple,
      WeekStartedEvent.OutputObject
    >;
    WeekStarted: TypedContractEvent<
      WeekStartedEvent.InputTuple,
      WeekStartedEvent.OutputTuple,
      WeekStartedEvent.OutputObject
    >;
  };
}
