/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPayer,
  IPayerInterface,
} from "../../../../contracts/reactive-lib/interfaces/IPayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class IPayer__factory {
  static readonly abi = _abi;
  static createInterface(): IPayerInterface {
    return new Interface(_abi) as IPayerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPayer {
    return new Contract(address, _abi, runner) as unknown as IPayer;
  }
}
