/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPayable,
  IPayableInterface,
} from "../../../../contracts/reactive-lib/interfaces/IPayable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
    ],
    name: "debt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class IPayable__factory {
  static readonly abi = _abi;
  static createInterface(): IPayableInterface {
    return new Interface(_abi) as IPayableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPayable {
    return new Contract(address, _abi, runner) as unknown as IPayable;
  }
}
