/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReactive,
  IReactiveInterface,
} from "../../../../contracts/reactive-lib/interfaces/IReactive";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "chain_id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint64",
        name: "gas_limit",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "Callback",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "chain_id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "_contract",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "topic_0",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "topic_1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "topic_2",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "topic_3",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "block_number",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "op_code",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "block_hash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tx_hash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "log_index",
            type: "uint256",
          },
        ],
        internalType: "struct IReactive.LogRecord",
        name: "log",
        type: "tuple",
      },
    ],
    name: "react",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class IReactive__factory {
  static readonly abi = _abi;
  static createInterface(): IReactiveInterface {
    return new Interface(_abi) as IReactiveInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReactive {
    return new Contract(address, _abi, runner) as unknown as IReactive;
  }
}
