/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISystemContract,
  ISystemContractInterface,
} from "../../../../contracts/reactive-lib/interfaces/ISystemContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
    ],
    name: "debt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chain_id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "topic_0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_3",
        type: "uint256",
      },
    ],
    name: "subscribe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chain_id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "topic_0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_3",
        type: "uint256",
      },
    ],
    name: "unsubscribe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class ISystemContract__factory {
  static readonly abi = _abi;
  static createInterface(): ISystemContractInterface {
    return new Interface(_abi) as ISystemContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISystemContract {
    return new Contract(address, _abi, runner) as unknown as ISystemContract;
  }
}
