/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISubscriptionServiceInterface extends Interface {
  getFunction(
    nameOrSignature: "debt" | "subscribe" | "unsubscribe"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "debt", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "debt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;
}

export interface ISubscriptionService extends BaseContract {
  connect(runner?: ContractRunner | null): ISubscriptionService;
  waitForDeployment(): Promise<this>;

  interface: ISubscriptionServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  debt: TypedContractMethod<[_contract: AddressLike], [bigint], "view">;

  subscribe: TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  unsubscribe: TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "debt"
  ): TypedContractMethod<[_contract: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unsubscribe"
  ): TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
