/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IValcoreReactiveTrigger } from "./IValcoreReactiveTrigger";
export type { ValcoreReactiveDispatcher } from "./ValcoreReactiveDispatcher";
