/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValcoreReactiveTrigger,
  IValcoreReactiveTriggerInterface,
} from "../../../contracts/ValcoreReactiveDispatcher.sol/IValcoreReactiveTrigger";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "gasLimit",
        type: "uint64",
      },
    ],
    name: "trigger",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValcoreReactiveTrigger__factory {
  static readonly abi = _abi;
  static createInterface(): IValcoreReactiveTriggerInterface {
    return new Interface(_abi) as IValcoreReactiveTriggerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValcoreReactiveTrigger {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IValcoreReactiveTrigger;
  }
}
