/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IValcoreLifecycleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveFinalizationWithIntent"
      | "createWeekWithIntent"
      | "finalizeWeekWithIntent"
      | "forceFinalizeWeekWithIntent"
      | "forceLockWeekWithIntent"
      | "forceStartWeekWithIntent"
      | "lockWeekWithIntent"
      | "rejectFinalizationWithIntent"
      | "startWeekWithIntent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveFinalizationWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createWeekWithIntent",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWeekWithIntent",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceFinalizeWeekWithIntent",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceLockWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceStartWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectFinalizationWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startWeekWithIntent",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveFinalizationWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceFinalizeWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLockWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceStartWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockWeekWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectFinalizationWithIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startWeekWithIntent",
    data: BytesLike
  ): Result;
}

export interface IValcoreLifecycle extends BaseContract {
  connect(runner?: ContractRunner | null): IValcoreLifecycle;
  waitForDeployment(): Promise<this>;

  interface: IValcoreLifecycleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveFinalizationWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  finalizeWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  forceFinalizeWeekWithIntent: TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  forceLockWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceStartWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectFinalizationWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  startWeekWithIntent: TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveFinalizationWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceFinalizeWeekWithIntent"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceLockWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceStartWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectFinalizationWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startWeekWithIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
