/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AbstractCallback,
  AbstractCallbackInterface,
} from "../../../../contracts/reactive-lib/abstract-base/AbstractCallback";

const _abi = [
  {
    inputs: [],
    name: "coverDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class AbstractCallback__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractCallbackInterface {
    return new Interface(_abi) as AbstractCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AbstractCallback {
    return new Contract(address, _abi, runner) as unknown as AbstractCallback;
  }
}
