/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ValcoreReactiveReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coverDebt"
      | "owner"
      | "pay"
      | "reactiveSender"
      | "rxApprove"
      | "rxCreateWeek"
      | "rxFinalize"
      | "rxReject"
      | "rxTransition"
      | "setAuthorizedSender"
      | "setReactiveSender"
      | "transferOwnership"
      | "valcore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedSenderUpdated"
      | "OwnershipTransferred"
      | "ReactiveLifecycleExecuted"
      | "ReactiveSenderUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "coverDebt", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "reactiveSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rxApprove",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rxCreateWeek",
    values: [
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rxFinalize",
    values: [
      AddressLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rxReject",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rxTransition",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedSender",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReactiveSender",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "valcore", values?: undefined): string;

  decodeFunctionResult(functionFragment: "coverDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactiveSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rxApprove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rxCreateWeek",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rxFinalize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rxReject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rxTransition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReactiveSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valcore", data: BytesLike): Result;
}

export namespace AuthorizedSenderUpdatedEvent {
  export type InputTuple = [sender: AddressLike, allowed: boolean];
  export type OutputTuple = [sender: string, allowed: boolean];
  export interface OutputObject {
    sender: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactiveLifecycleExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    action: BigNumberish,
    weekId: BigNumberish
  ];
  export type OutputTuple = [intentId: string, action: bigint, weekId: bigint];
  export interface OutputObject {
    intentId: string;
    action: bigint;
    weekId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactiveSenderUpdatedEvent {
  export type InputTuple = [
    previousSender: AddressLike,
    newSender: AddressLike
  ];
  export type OutputTuple = [previousSender: string, newSender: string];
  export interface OutputObject {
    previousSender: string;
    newSender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValcoreReactiveReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): ValcoreReactiveReceiver;
  waitForDeployment(): Promise<this>;

  interface: ValcoreReactiveReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coverDebt: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  pay: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  reactiveSender: TypedContractMethod<[], [string], "view">;

  rxApprove: TypedContractMethod<
    [sender: AddressLike, intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rxCreateWeek: TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  rxFinalize: TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish,
      useForce: boolean
    ],
    [void],
    "nonpayable"
  >;

  rxReject: TypedContractMethod<
    [sender: AddressLike, intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rxTransition: TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      action: BigNumberish,
      weekId: BigNumberish,
      useForce: boolean
    ],
    [void],
    "nonpayable"
  >;

  setAuthorizedSender: TypedContractMethod<
    [sender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setReactiveSender: TypedContractMethod<
    [newReactiveSender: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  valcore: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coverDebt"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reactiveSender"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rxApprove"
  ): TypedContractMethod<
    [sender: AddressLike, intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rxCreateWeek"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      weekId: BigNumberish,
      startAt: BigNumberish,
      lockAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rxFinalize"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      weekId: BigNumberish,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      retainedFee: BigNumberish,
      useForce: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rxReject"
  ): TypedContractMethod<
    [sender: AddressLike, intentId: BytesLike, weekId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rxTransition"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      intentId: BytesLike,
      action: BigNumberish,
      weekId: BigNumberish,
      useForce: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedSender"
  ): TypedContractMethod<
    [sender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReactiveSender"
  ): TypedContractMethod<
    [newReactiveSender: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "valcore"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AuthorizedSenderUpdated"
  ): TypedContractEvent<
    AuthorizedSenderUpdatedEvent.InputTuple,
    AuthorizedSenderUpdatedEvent.OutputTuple,
    AuthorizedSenderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReactiveLifecycleExecuted"
  ): TypedContractEvent<
    ReactiveLifecycleExecutedEvent.InputTuple,
    ReactiveLifecycleExecutedEvent.OutputTuple,
    ReactiveLifecycleExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ReactiveSenderUpdated"
  ): TypedContractEvent<
    ReactiveSenderUpdatedEvent.InputTuple,
    ReactiveSenderUpdatedEvent.OutputTuple,
    ReactiveSenderUpdatedEvent.OutputObject
  >;

  filters: {
    "AuthorizedSenderUpdated(address,bool)": TypedContractEvent<
      AuthorizedSenderUpdatedEvent.InputTuple,
      AuthorizedSenderUpdatedEvent.OutputTuple,
      AuthorizedSenderUpdatedEvent.OutputObject
    >;
    AuthorizedSenderUpdated: TypedContractEvent<
      AuthorizedSenderUpdatedEvent.InputTuple,
      AuthorizedSenderUpdatedEvent.OutputTuple,
      AuthorizedSenderUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReactiveLifecycleExecuted(bytes32,uint8,uint256)": TypedContractEvent<
      ReactiveLifecycleExecutedEvent.InputTuple,
      ReactiveLifecycleExecutedEvent.OutputTuple,
      ReactiveLifecycleExecutedEvent.OutputObject
    >;
    ReactiveLifecycleExecuted: TypedContractEvent<
      ReactiveLifecycleExecutedEvent.InputTuple,
      ReactiveLifecycleExecutedEvent.OutputTuple,
      ReactiveLifecycleExecutedEvent.OutputObject
    >;

    "ReactiveSenderUpdated(address,address)": TypedContractEvent<
      ReactiveSenderUpdatedEvent.InputTuple,
      ReactiveSenderUpdatedEvent.OutputTuple,
      ReactiveSenderUpdatedEvent.OutputObject
    >;
    ReactiveSenderUpdated: TypedContractEvent<
      ReactiveSenderUpdatedEvent.InputTuple,
      ReactiveSenderUpdatedEvent.OutputTuple,
      ReactiveSenderUpdatedEvent.OutputObject
    >;
  };
}
